### ISSUE TITLE
 Space-Travelers-Hub - Tasks Distribution

### ISSUE THREAD

**Issue by Metaverse-Nabeel** [Metaverse-Nabeel/Space-Travelers-Hub#25]
**Project Link:** `https://github.com/Metaverse-Nabeel/Space-Travelers-Hub/projects/1`

**Group Members**

This project would be done by @Metaverse-Nabeel `Solo`. Due to Internet Issues resulting in hindering the group project activity. I have removed tasks for the Third Team member but the Second Team member's tasks are still present. Please guide me so that I can remove those tasks and just focus on First Team Member's tasks to complete this project within the timeline.

**Comment by Metaverse-Nabeel** [comment]
Hello @julie-ify 

I hope you are doing well. I have made the changes mentioned by you. I shall first focus on my tasks which are compulsory to complete the week and after that, if I found time I will complete the other tasks for the mission.

Thank you so much

Regards

**Comment by Owusu-Desmond** [comment]
Hi @Metaverse-Nabeel , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/l0Iyl55kTeh71nTXy/giphy.gif"/>

## Highlights✅
📌 Great working on the setup of the project board ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
